#!/usr/bin/env python3
"""Per indexer-day QoS figures computed straight from the oracle's raw payloads, independently of the
nest, and emitted as the reference table for checks/parity-*.sql.

The payload directory holds one file per indexer-attempt document, named `<bucket_end>_<cid>.json`
(optionally `.gz`), which is what fetching the CIDs posted to the DataEdge on Gnosis produces. The
arithmetic is the RFC's, stated once here and once in views/30-qos-daily.sql, and the check exists so
the two can never quietly disagree:

  success_rate  = sum(num_200) / sum(query_count)
  latency_ms    = sum(avg_indexer_latency_ms * query_count) / sum(query_count)
  blocks_behind = sum(avg_indexer_blocks_behind * query_count) / sum(query_count)
  bad bucket    = the indexer's bucket with >= 50 queries and < 90% success
  day           = UTC day of the bucket's start_epoch

Usage: python3 scripts/parity-reference.py <payload-dir> <YYYY-MM-DD> [--sql]
"""
import collections, datetime as dt, glob, gzip, json, os, sys

def rows_of(path):
    opener = gzip.open if path.endswith('.gz') else open
    with opener(path, 'rb') as fh:
        return json.load(fh)

def main():
    src, day = sys.argv[1], dt.date.fromisoformat(sys.argv[2])
    as_sql = '--sql' in sys.argv
    lo = int(dt.datetime(day.year, day.month, day.day, tzinfo=dt.timezone.utc).timestamp())
    hi = lo + 86400
    acc = collections.defaultdict(lambda: {'qc': 0.0, 'n200': 0.0, 'latw': 0.0, 'bbw': 0.0, 'fees': 0.0})
    bucket = collections.defaultdict(lambda: [0.0, 0.0])
    seen = collections.defaultdict(set)
    docs = 0
    for path in sorted(glob.glob(os.path.join(src, '*.json*'))):
        rows = rows_of(path)
        if not rows or not (lo <= rows[0]['start_epoch'] < hi):
            continue
        docs += 1
        for r in rows:
            if not (lo <= r['start_epoch'] < hi):
                continue
            ind = r['indexer_wallet'].lower()
            qc = float(r['query_count'])
            n200 = r.get('num_indexer_200_responses')
            n200 = float(r['proportion_indexer_200_responses']) * qc if n200 is None else float(n200)
            a = acc[ind]
            a['qc'] += qc
            a['n200'] += n200
            a['latw'] += float(r['avg_indexer_latency_ms']) * qc
            a['bbw'] += float(r['avg_indexer_blocks_behind']) * qc
            a['fees'] += float(r['total_query_fees'])
            b = bucket[(ind, r['start_epoch'])]
            b[0] += qc
            b[1] += n200
            seen[ind].add(r['start_epoch'])
    out = []
    for ind in sorted(acc):
        a = acc[ind]
        mine = sorted(((ts, v) for (i, ts), v in bucket.items() if i == ind))
        credible = [(ts, v) for ts, v in mine if v[0] >= 50]
        worst = min(credible, key=lambda kv: (kv[1][1] / kv[1][0], kv[0])) if credible else None
        out.append({
            'indexer': ind,
            'query_count': a['qc'],
            'num_200': a['n200'],
            'success_rate': a['n200'] / a['qc'] if a['qc'] else None,
            'latency_ms': a['latw'] / a['qc'] if a['qc'] else None,
            'blocks_behind': a['bbw'] / a['qc'] if a['qc'] else None,
            'total_query_fees': a['fees'],
            'buckets': len(seen[ind]),
            'bad_buckets': sum(1 for _, v in credible if v[1] < 0.9 * v[0]),
            'worst_bucket_start': worst[0] if worst else None,
        })
    if not as_sql:
        json.dump({'day': day.isoformat(), 'documents': docs, 'indexers': out}, sys.stdout, indent=1)
        return
    lit = lambda v: 'NULL' if v is None else (repr(v) if not isinstance(v, str) else f"'{v}'")
    cols = list(out[0])
    print(f'-- {docs} documents, {len(out)} indexers, generated by scripts/parity-reference.py')
    print('SELECT * FROM (VALUES')
    print(',\n'.join('  (' + ', '.join(lit(r[c]) for c in cols) + ')' for r in out))
    print(f') AS ref({", ".join(cols)})')

if __name__ == '__main__':
    main()
